# Copyright 2026 INNO LOTUS PTY LTD
# SPDX-License-Identifier: Apache-2.0

"""NPS NWP — Neural Web Protocol frames and async client."""

from nps_sdk.nwp.frames import (
    NWP_TOPOLOGY_SNAPSHOT,
    NWP_TOPOLOGY_STREAM,
    BridgeNodeSpec,
    QueryOrderClause,
    ActionFrame,
    AsyncActionResponse,
    QueryFrame,
    SubscribeFrame,
    TopologyEvent,
    TopologyMember,
    TopologySnapshotRequest,
    TopologyStreamRequest,
    VectorSearchOptions,
)
from nps_sdk.nwp.client import NwpClient
from nps_sdk.nwp import error_codes
from nps_sdk.nwp.error_codes import NWP_ERROR_TO_NPS_STATUS
from nps_sdk.nwp.anchor_client import (
    MemberInfo,
    TopologySnapshot,
    TopologyFilter,
    MemberChanges,
    TopologyEvent,
    MemberJoined,
    MemberLeft,
    MemberUpdated,
    AnchorState,
    ResyncRequired,
    AnchorTopologyException,
    AnchorNodeClient,
)
from nps_sdk.nwp.cgn import (
    estimate_cgn,
    estimate_cgn_json,
    estimate_cgn_rows,
    TokenBudgetMeta,
    BudgetExceededError,
)
from nps_sdk.nwp.bridge import (
    BridgeProtocols,
    BridgeNodeDescriptor,
    BridgeTarget,
    NODE_TYPE_BRIDGE,
)
from nps_sdk.nwp import inbound
from nps_sdk.nwp.inbound import (
    A2aInboundServer,
    BridgeErrorCodes,
    BridgeErrorMap,
    BridgeInboundOptions,
    BridgeJsonRpcErrorCodes,
    BridgeJsonRpcRequest,
    BridgeJsonRpcResponse,
    BridgeServerAction,
    GrpcInboundService,
    GrpcRpcError,
    HttpNwpBackend,
    InProcessNwpBackend,
    McpInboundServer,
    McpToolName,
    NwpActionDescriptor,
    NwpBackend,
    NwpNodeDescriptor,
    NwpNodeRole,
    NwpResult,
    NwpUpstream,
    create_backends,
)
from nps_sdk.nwp.reputation import (
    ReputationRule,
    ReputationPolicy,
    RepOutcome,
    ReputationDecision,
    IReputationEvaluator,
    DefaultReputationEvaluator,
    default_reputation_evaluator,
)
from nps_sdk.nwp.memory_node_server import (
    MemoryNodeField,
    MemoryNodeSchema,
    MemoryNodeOptions,
    MemoryNodeRow,
    MemoryNodeQueryResult,
    IMemoryNodeProvider,
    NodeRequest,
    NodeResponse,
    MemoryNodeServer,
)
from nps_sdk.nwp.native_server import (
    NativeActionHandler,
    NativeQueryHandler,
    NwpNativeNodeServer,
)
from nps_sdk.nwp.llm import (
    CAPABILITY_LLM_COMPLETE,
    CAPABILITY_LLM_CONTEXT,
    CAPABILITY_LLM_STREAM,
    CAPABILITY_LLM_TOOL_CALL,
    LLM_COMPLETE,
    LLM_CONTEXT_RELEASE,
    LLM_CONTEXT_STATUS,
    LlmCompleteActionRequest,
    LlmCompleteActionResponse,
    LlmCompleteStreamChunkDto,
    LlmContextOperation,
    LlmContextReceiptDto,
    LlmContextReleaseRequestDto,
    LlmContextRequestDto,
    LlmContextState,
    LlmContextStatusDto,
    LlmContextStatusRequestDto,
    LlmMessageDto,
    LlmStopReason,
    LlmToolCallDto,
    LlmToolDefinitionDto,
    LlmUsageDto,
    ToolParameterDto,
    context_release_action_frame,
    context_status_action_frame,
)
from nps_sdk.nwp.context_store import (
    InMemoryLlmContextStore,
    LlmContextBinding,
    LlmContextMutationRequest,
    LlmContextMutationReservation,
    LlmContextOwner,
    LlmContextSnapshot,
    LlmContextStoreError,
    LlmContextStoreDescriptor,
    LlmContextStoreOptions,
)
from nps_sdk.nwp.llm_action_server import (
    LlmAuthorizationStage,
    LlmContextAuthorizer,
    StatefulLlmActionOptions,
    StatefulLlmActionProvider,
)
from nps_sdk.nwp.anchor_server import (
    AnchorEpochGuard,
    AnchorRole,
    TopologyProtocolError,
    TopologyWire,
    AnchorNodeApp,
    AnchorNodeOptions,
    AnchorActionSpec,
    AnchorActionError,
    AnchorInvokeHandler,
    AnchorTopologyService,
    InMemoryAnchorTopologyService,
    AnchorRateLimiter,
    AllowAllRateLimiter,
    InvokeContext,
)

__all__ = [
    "NWP_TOPOLOGY_SNAPSHOT",
    "NWP_TOPOLOGY_STREAM",
    "BridgeNodeSpec",
    "QueryOrderClause",
    "VectorSearchOptions",
    "QueryFrame",
    "TopologyEvent",
    "TopologyMember",
    "TopologySnapshotRequest",
    "TopologyStreamRequest",
    "ActionFrame",
    "AsyncActionResponse",
    "SubscribeFrame",
    "NwpClient",
    # error codes
    "error_codes",
    "NWP_ERROR_TO_NPS_STATUS",
    # Anchor topology
    "MemberInfo",
    "TopologySnapshot",
    "TopologyFilter",
    "MemberChanges",
    "TopologyEvent",
    "MemberJoined",
    "MemberLeft",
    "MemberUpdated",
    "AnchorState",
    "ResyncRequired",
    "AnchorTopologyException",
    "AnchorNodeClient",
    # CGN token-budget helpers
    "estimate_cgn",
    "estimate_cgn_json",
    "estimate_cgn_rows",
    "TokenBudgetMeta",
    "BudgetExceededError",
    # Inbound Bridge servers (NPS-CR-0010)
    "inbound",
    "A2aInboundServer",
    "BridgeErrorCodes",
    "BridgeErrorMap",
    "BridgeInboundOptions",
    "BridgeJsonRpcErrorCodes",
    "BridgeJsonRpcRequest",
    "BridgeJsonRpcResponse",
    "BridgeServerAction",
    "GrpcInboundService",
    "GrpcRpcError",
    "HttpNwpBackend",
    "InProcessNwpBackend",
    "McpInboundServer",
    "McpToolName",
    "NwpActionDescriptor",
    "NwpBackend",
    "NwpNodeDescriptor",
    "NwpNodeRole",
    "NwpResult",
    "NwpUpstream",
    "create_backends",
    # Bridge Node types
    "BridgeProtocols",
    "BridgeNodeDescriptor",
    "BridgeTarget",
    "NODE_TYPE_BRIDGE",
    # Reputation policy (RFC-0005)
    "ReputationRule",
    "ReputationPolicy",
    "RepOutcome",
    "ReputationDecision",
    "IReputationEvaluator",
    "DefaultReputationEvaluator",
    "default_reputation_evaluator",
    # Memory Node server
    "MemoryNodeField",
    "MemoryNodeSchema",
    "MemoryNodeOptions",
    "MemoryNodeRow",
    "MemoryNodeQueryResult",
    "IMemoryNodeProvider",
    "NodeRequest",
    "NodeResponse",
    "MemoryNodeServer",
    "NativeActionHandler",
    "NativeQueryHandler",
    "NwpNativeNodeServer",
    "LLM_COMPLETE",
    "LLM_CONTEXT_STATUS",
    "LLM_CONTEXT_RELEASE",
    "CAPABILITY_LLM_COMPLETE",
    "CAPABILITY_LLM_CONTEXT",
    "CAPABILITY_LLM_STREAM",
    "CAPABILITY_LLM_TOOL_CALL",
    "LlmStopReason",
    "LlmContextOperation",
    "LlmContextState",
    "LlmToolCallDto",
    "ToolParameterDto",
    "LlmToolDefinitionDto",
    "LlmMessageDto",
    "LlmContextRequestDto",
    "LlmContextReceiptDto",
    "LlmContextStatusRequestDto",
    "LlmContextReleaseRequestDto",
    "LlmContextStatusDto",
    "LlmUsageDto",
    "LlmCompleteActionRequest",
    "LlmCompleteActionResponse",
    "LlmCompleteStreamChunkDto",
    "context_status_action_frame",
    "context_release_action_frame",
    "LlmContextOwner",
    "LlmContextBinding",
    "LlmContextMutationRequest",
    "LlmContextMutationReservation",
    "LlmContextSnapshot",
    "LlmContextStoreError",
    "LlmContextStoreDescriptor",
    "LlmContextStoreOptions",
    "InMemoryLlmContextStore",
    "LlmAuthorizationStage",
    "LlmContextAuthorizer",
    "StatefulLlmActionOptions",
    "StatefulLlmActionProvider",
    # Anchor Node server (alpha.13 client+server parity)
    "AnchorEpochGuard",
    "AnchorRole",
    "TopologyProtocolError",
    "TopologyWire",
    "AnchorNodeApp",
    "AnchorNodeOptions",
    "AnchorActionSpec",
    "AnchorActionError",
    "AnchorInvokeHandler",
    "AnchorTopologyService",
    "InMemoryAnchorTopologyService",
    "AnchorRateLimiter",
    "AllowAllRateLimiter",
    "InvokeContext",
]
