# Copyright 2026 INNO LOTUS PTY LTD
# SPDX-License-Identifier: Apache-2.0

"""NPS NWP — Neural Web Protocol frames and async client."""

from nps_sdk.nwp.frames import (
    NWP_TOPOLOGY_SNAPSHOT,
    NWP_TOPOLOGY_STREAM,
    BridgeNodeSpec,
    QueryOrderClause,
    ActionFrame,
    AsyncActionResponse,
    QueryFrame,
    SubscribeFrame,
    TopologyEvent,
    TopologyMember,
    TopologySnapshotRequest,
    TopologyStreamRequest,
    VectorSearchOptions,
)
from nps_sdk.nwp.client import NwpClient
from nps_sdk.nwp import error_codes
from nps_sdk.nwp.error_codes import NWP_ERROR_TO_NPS_STATUS
from nps_sdk.nwp.anchor_client import (
    MemberInfo,
    TopologySnapshot,
    TopologyFilter,
    MemberChanges,
    TopologyEvent,
    MemberJoined,
    MemberLeft,
    MemberUpdated,
    AnchorState,
    ResyncRequired,
    AnchorTopologyException,
    AnchorNodeClient,
)
from nps_sdk.nwp.cgn import (
    estimate_cgn,
    estimate_cgn_json,
    estimate_cgn_rows,
    TokenBudgetMeta,
    BudgetExceededError,
)
from nps_sdk.nwp.bridge import (
    BridgeProtocols,
    BridgeNodeDescriptor,
    BridgeTarget,
    NODE_TYPE_BRIDGE,
    BridgeErrorCodes,
    BridgeDispatchException,
    BridgeJsonRpcRequest,
    BridgeJsonRpcResponse,
    BridgeJsonRpcError,
    BridgeJsonRpcErrorCodes,
    IBridgeDispatcher,
    HttpBridgeDispatcher,
    GrpcBridgeDispatcher,
    JsonRpcBridgeDispatcher,
    McpBridgeDispatcher,
    A2aBridgeDispatcher,
    BridgeDispatcherRegistry,
    BridgeNode,
    McpServerProtocol,
    A2aServerProtocol,
    A2aTaskState,
    BridgeServerAction,
    BridgeServerOptions,
    IBridgeServerActionInvoker,
    BridgeServerActionInvoker,
    to_tool_name,
    McpServerBridge,
    A2aServerBridge,
    BridgeNodeMiddleware,
    BridgeNodeOptions,
    BridgeServerMiddleware,
)
from nps_sdk.nwp.reputation import (
    ReputationRule,
    ReputationPolicy,
    RepOutcome,
    ReputationDecision,
    IReputationEvaluator,
    DefaultReputationEvaluator,
    default_reputation_evaluator,
)
from nps_sdk.nwp.memory_node_server import (
    MemoryNodeField,
    MemoryNodeSchema,
    MemoryNodeOptions,
    MemoryNodeRow,
    MemoryNodeQueryResult,
    IMemoryNodeProvider,
    InMemoryMemoryNodeProvider,
    evaluate_filter,
    NodeRequest,
    NodeResponse,
    MemoryNodeServer,
)
from nps_sdk.nwp.action_node_server import (
    ActionNodeApp,
    ActionNodeOptions,
    ActionSpec,
    ActionContext,
    ActionExecutionResult,
    ActionExecutionError,
    IActionNodeProvider,
    ActionTaskRecord,
    IActionTaskStore,
    InMemoryActionTaskStore,
    IdempotentEntry,
    IIdempotencyCache,
    InMemoryIdempotencyCache,
    ActionCallbackValidator,
    is_private_host,
    SYSTEM_TASK_STATUS,
    SYSTEM_TASK_CANCEL,
)
from nps_sdk.nwp.complex_node_server import (
    ComplexNodeApp,
    ComplexNodeOptions,
    ComplexGraphRef,
    IComplexNodeProvider,
    NullComplexNodeProvider,
    ComplexChildUrlValidator,
    ABSOLUTE_MAX_DEPTH,
    TRACE_HEADER,
)
from nps_sdk.nwp.native_server import (
    NativeActionHandler,
    NativeQueryHandler,
    NwpNativeNodeServer,
)
from nps_sdk.nwp.anchor_server import (
    AnchorNodeApp,
    AnchorNodeOptions,
    AnchorActionSpec,
    AnchorActionError,
    AnchorInvokeHandler,
    AnchorTopologyService,
    InMemoryAnchorTopologyService,
    AnchorRateLimiter,
    AllowAllRateLimiter,
    InvokeContext,
)
from nps_sdk.nwp import instrumentation
from nps_sdk.nwp.memory_node_sql import (
    DatabaseDialect,
    ParamStyle,
    NwpFilterError,
    NwpFilterTranslator,
    SqlQueryBuilder,
    encode_cursor,
    decode_cursor,
    QUERY_FILTER_INVALID,
    QUERY_FIELD_UNKNOWN,
)
from nps_sdk.nwp.memory_node_providers import (
    IAsyncDbExecutor,
    SqlMemoryNodeProvider,
    SqliteDbExecutor,
    SqliteMemoryNodeProvider,
)

__all__ = [
    "NWP_TOPOLOGY_SNAPSHOT",
    "NWP_TOPOLOGY_STREAM",
    "BridgeNodeSpec",
    "QueryOrderClause",
    "VectorSearchOptions",
    "QueryFrame",
    "TopologyEvent",
    "TopologyMember",
    "TopologySnapshotRequest",
    "TopologyStreamRequest",
    "ActionFrame",
    "AsyncActionResponse",
    "SubscribeFrame",
    "NwpClient",
    # error codes
    "error_codes",
    "NWP_ERROR_TO_NPS_STATUS",
    # Anchor topology
    "MemberInfo",
    "TopologySnapshot",
    "TopologyFilter",
    "MemberChanges",
    "TopologyEvent",
    "MemberJoined",
    "MemberLeft",
    "MemberUpdated",
    "AnchorState",
    "ResyncRequired",
    "AnchorTopologyException",
    "AnchorNodeClient",
    # CGN token-budget helpers
    "estimate_cgn",
    "estimate_cgn_json",
    "estimate_cgn_rows",
    "TokenBudgetMeta",
    "BudgetExceededError",
    # Bridge Node types
    "BridgeProtocols",
    "BridgeNodeDescriptor",
    "BridgeTarget",
    "NODE_TYPE_BRIDGE",
    # Bridge dispatcher subsystem (NPS-CR-0001)
    "BridgeErrorCodes",
    "BridgeDispatchException",
    "BridgeJsonRpcRequest",
    "BridgeJsonRpcResponse",
    "BridgeJsonRpcError",
    "BridgeJsonRpcErrorCodes",
    "IBridgeDispatcher",
    "HttpBridgeDispatcher",
    "GrpcBridgeDispatcher",
    "JsonRpcBridgeDispatcher",
    "McpBridgeDispatcher",
    "A2aBridgeDispatcher",
    "BridgeDispatcherRegistry",
    "BridgeNode",
    "McpServerProtocol",
    "A2aServerProtocol",
    "A2aTaskState",
    "BridgeServerAction",
    "BridgeServerOptions",
    "IBridgeServerActionInvoker",
    "BridgeServerActionInvoker",
    "to_tool_name",
    "McpServerBridge",
    "A2aServerBridge",
    "BridgeNodeMiddleware",
    "BridgeNodeOptions",
    "BridgeServerMiddleware",
    # Reputation policy (RFC-0005)
    "ReputationRule",
    "ReputationPolicy",
    "RepOutcome",
    "ReputationDecision",
    "IReputationEvaluator",
    "DefaultReputationEvaluator",
    "default_reputation_evaluator",
    # Memory Node server
    "MemoryNodeField",
    "MemoryNodeSchema",
    "MemoryNodeOptions",
    "MemoryNodeRow",
    "MemoryNodeQueryResult",
    "IMemoryNodeProvider",
    "InMemoryMemoryNodeProvider",
    "evaluate_filter",
    "NodeRequest",
    "NodeResponse",
    "MemoryNodeServer",
    # Action Node server
    "ActionNodeApp",
    "ActionNodeOptions",
    "ActionSpec",
    "ActionContext",
    "ActionExecutionResult",
    "ActionExecutionError",
    "IActionNodeProvider",
    "ActionTaskRecord",
    "IActionTaskStore",
    "InMemoryActionTaskStore",
    "IdempotentEntry",
    "IIdempotencyCache",
    "InMemoryIdempotencyCache",
    "ActionCallbackValidator",
    "is_private_host",
    "SYSTEM_TASK_STATUS",
    "SYSTEM_TASK_CANCEL",
    # Complex Node server
    "ComplexNodeApp",
    "ComplexNodeOptions",
    "ComplexGraphRef",
    "IComplexNodeProvider",
    "NullComplexNodeProvider",
    "ComplexChildUrlValidator",
    "ABSOLUTE_MAX_DEPTH",
    "TRACE_HEADER",
    "NativeActionHandler",
    "NativeQueryHandler",
    "NwpNativeNodeServer",
    # Anchor Node server (alpha.13 client+server parity)
    "AnchorNodeApp",
    "AnchorNodeOptions",
    "AnchorActionSpec",
    "AnchorActionError",
    "AnchorInvokeHandler",
    "AnchorTopologyService",
    "InMemoryAnchorTopologyService",
    "AnchorRateLimiter",
    "AllowAllRateLimiter",
    "InvokeContext",
    # Telemetry / instrumentation ([I] band)
    "instrumentation",
    # Filter→SQL translation + SQL providers ([I] band)
    "DatabaseDialect",
    "ParamStyle",
    "NwpFilterError",
    "NwpFilterTranslator",
    "SqlQueryBuilder",
    "encode_cursor",
    "decode_cursor",
    "QUERY_FILTER_INVALID",
    "QUERY_FIELD_UNKNOWN",
    "IAsyncDbExecutor",
    "SqlMemoryNodeProvider",
    "SqliteDbExecutor",
    "SqliteMemoryNodeProvider",
]
