# Copyright 2026 INNO LOTUS PTY LTD
# SPDX-License-Identifier: Apache-2.0

"""NWP error code wire constants — mirror of `spec/error-codes.md` NWP section."""

from __future__ import annotations

# ── Auth ─────────────────────────────────────────────────────────────────────
AUTH_NID_SCOPE_VIOLATION    = "NWP-AUTH-NID-SCOPE-VIOLATION"
AUTH_NID_EXPIRED            = "NWP-AUTH-NID-EXPIRED"
AUTH_NID_REVOKED            = "NWP-AUTH-NID-REVOKED"
AUTH_NID_UNTRUSTED_ISSUER   = "NWP-AUTH-NID-UNTRUSTED-ISSUER"
AUTH_NID_CAPABILITY_MISSING = "NWP-AUTH-NID-CAPABILITY-MISSING"
AUTH_ASSURANCE_TOO_LOW      = "NWP-AUTH-ASSURANCE-TOO-LOW"
AUTH_REPUTATION_BLOCKED     = "NWP-AUTH-REPUTATION-BLOCKED"

# ── Query ─────────────────────────────────────────────────────────────────────
QUERY_FILTER_INVALID        = "NWP-QUERY-FILTER-INVALID"
QUERY_FIELD_UNKNOWN         = "NWP-QUERY-FIELD-UNKNOWN"
QUERY_CURSOR_INVALID        = "NWP-QUERY-CURSOR-INVALID"
QUERY_REGEX_UNSAFE          = "NWP-QUERY-REGEX-UNSAFE"
QUERY_VECTOR_UNSUPPORTED    = "NWP-QUERY-VECTOR-UNSUPPORTED"
QUERY_AGGREGATE_UNSUPPORTED = "NWP-QUERY-AGGREGATE-UNSUPPORTED"
QUERY_AGGREGATE_INVALID     = "NWP-QUERY-AGGREGATE-INVALID"
QUERY_STREAM_UNSUPPORTED    = "NWP-QUERY-STREAM-UNSUPPORTED"

# ── Action ────────────────────────────────────────────────────────────────────
ACTION_NOT_FOUND             = "NWP-ACTION-NOT-FOUND"
ACTION_PARAMS_INVALID        = "NWP-ACTION-PARAMS-INVALID"
ACTION_IDEMPOTENCY_CONFLICT  = "NWP-ACTION-IDEMPOTENCY-CONFLICT"

# ── Task ──────────────────────────────────────────────────────────────────────
TASK_NOT_FOUND          = "NWP-TASK-NOT-FOUND"
TASK_ALREADY_CANCELLED  = "NWP-TASK-ALREADY-CANCELLED"
TASK_ALREADY_COMPLETED  = "NWP-TASK-ALREADY-COMPLETED"
TASK_ALREADY_FAILED     = "NWP-TASK-ALREADY-FAILED"

# ── Subscribe ─────────────────────────────────────────────────────────────────
SUBSCRIBE_STREAM_NOT_FOUND  = "NWP-SUBSCRIBE-STREAM-NOT-FOUND"
SUBSCRIBE_LIMIT_EXCEEDED    = "NWP-SUBSCRIBE-LIMIT-EXCEEDED"
SUBSCRIBE_FILTER_UNSUPPORTED = "NWP-SUBSCRIBE-FILTER-UNSUPPORTED"
SUBSCRIBE_INTERRUPTED       = "NWP-SUBSCRIBE-INTERRUPTED"
SUBSCRIBE_SEQ_TOO_OLD       = "NWP-SUBSCRIBE-SEQ-TOO-OLD"

# ── Infrastructure ────────────────────────────────────────────────────────────
BUDGET_EXCEEDED          = "NWP-BUDGET-EXCEEDED"
CGN_LIMIT_EXCEEDED       = "NWP-CGN-LIMIT-EXCEEDED"
DEPTH_EXCEEDED           = "NWP-DEPTH-EXCEEDED"
GRAPH_CYCLE              = "NWP-GRAPH-CYCLE"
NODE_UNAVAILABLE         = "NWP-NODE-UNAVAILABLE"
RATE_LIMIT_EXCEEDED      = "NWP-RATE-LIMIT-EXCEEDED"

# ── Manifest ──────────────────────────────────────────────────────────────────
MANIFEST_VERSION_UNSUPPORTED = "NWP-MANIFEST-VERSION-UNSUPPORTED"
MANIFEST_NODE_TYPE_REMOVED   = "NWP-MANIFEST-NODE-TYPE-REMOVED"
MANIFEST_NODE_TYPE_UNKNOWN   = "NWP-MANIFEST-NODE-TYPE-UNKNOWN"

# ── Topology (alpha.11+) ───────────────────────────────────────────────────────
TOPOLOGY_UNAUTHORIZED       = "NWP-TOPOLOGY-UNAUTHORIZED"
TOPOLOGY_UNSUPPORTED_SCOPE  = "NWP-TOPOLOGY-UNSUPPORTED-SCOPE"
TOPOLOGY_DEPTH_UNSUPPORTED  = "NWP-TOPOLOGY-DEPTH-UNSUPPORTED"
TOPOLOGY_FILTER_UNSUPPORTED = "NWP-TOPOLOGY-FILTER-UNSUPPORTED"

# ── Reputation (RFC-0005 / alpha.11+) ─────────────────────────────────────────
REPUTATION_THROTTLED = "NWP-REPUTATION-THROTTLED"
REPUTATION_REJECTED  = "NWP-REPUTATION-REJECTED"
REPUTATION_BANNED    = "NWP-REPUTATION-BANNED"

# ── Reserved type (alpha.11+) ─────────────────────────────────────────────────
RESERVED_TYPE_UNSUPPORTED = "NWP-RESERVED-TYPE-UNSUPPORTED"

# ── NPS status mapping ────────────────────────────────────────────────────────
from nps_sdk.core.status_codes import (  # noqa: E402
    NPS_AUTH_FORBIDDEN,
    NPS_AUTH_UNAUTHENTICATED,
    NPS_CLIENT_BAD_FRAME,
    NPS_CLIENT_BAD_PARAM,
    NPS_CLIENT_CONFLICT,
    NPS_CLIENT_NOT_FOUND,
    NPS_CLIENT_UNPROCESSABLE,
    NPS_LIMIT_BUDGET,
    NPS_LIMIT_RATE,
    NPS_SERVER_UNAVAILABLE,
    NPS_SERVER_UNSUPPORTED,
)
# NWP-REPUTATION-THROTTLED maps to NPS-CLIENT-RATE-LIMITED per spec;
# the closest defined status code is NPS-LIMIT-RATE.
_NPS_CLIENT_RATE_LIMITED = "NPS-CLIENT-RATE-LIMITED"
_NPS_LIMIT_EXCEEDED      = "NPS-LIMIT-EXCEEDED"
_NPS_CLIENT_REQUEST_TOO_LARGE = "NPS-CLIENT-REQUEST-TOO-LARGE"

NWP_ERROR_TO_NPS_STATUS: dict[str, str] = {
    AUTH_NID_SCOPE_VIOLATION:       NPS_AUTH_FORBIDDEN,
    AUTH_NID_EXPIRED:               NPS_AUTH_UNAUTHENTICATED,
    AUTH_NID_REVOKED:               NPS_AUTH_UNAUTHENTICATED,
    AUTH_NID_UNTRUSTED_ISSUER:      NPS_AUTH_UNAUTHENTICATED,
    AUTH_NID_CAPABILITY_MISSING:    NPS_AUTH_FORBIDDEN,
    AUTH_ASSURANCE_TOO_LOW:         NPS_AUTH_FORBIDDEN,
    AUTH_REPUTATION_BLOCKED:        NPS_AUTH_FORBIDDEN,
    REPUTATION_THROTTLED:           _NPS_CLIENT_RATE_LIMITED,
    REPUTATION_REJECTED:            NPS_AUTH_FORBIDDEN,
    REPUTATION_BANNED:              NPS_AUTH_FORBIDDEN,
    QUERY_FILTER_INVALID:           NPS_CLIENT_BAD_PARAM,
    QUERY_FIELD_UNKNOWN:            NPS_CLIENT_BAD_PARAM,
    QUERY_CURSOR_INVALID:           NPS_CLIENT_BAD_PARAM,
    QUERY_REGEX_UNSAFE:             NPS_CLIENT_BAD_PARAM,
    QUERY_VECTOR_UNSUPPORTED:       NPS_SERVER_UNSUPPORTED,
    QUERY_AGGREGATE_UNSUPPORTED:    NPS_SERVER_UNSUPPORTED,
    QUERY_AGGREGATE_INVALID:        NPS_CLIENT_BAD_PARAM,
    QUERY_STREAM_UNSUPPORTED:       NPS_SERVER_UNSUPPORTED,
    ACTION_NOT_FOUND:               NPS_CLIENT_NOT_FOUND,
    ACTION_PARAMS_INVALID:          NPS_CLIENT_UNPROCESSABLE,
    ACTION_IDEMPOTENCY_CONFLICT:    NPS_CLIENT_CONFLICT,
    TASK_NOT_FOUND:                 NPS_CLIENT_NOT_FOUND,
    TASK_ALREADY_CANCELLED:         NPS_CLIENT_CONFLICT,
    TASK_ALREADY_COMPLETED:         NPS_CLIENT_CONFLICT,
    TASK_ALREADY_FAILED:            NPS_CLIENT_CONFLICT,
    SUBSCRIBE_STREAM_NOT_FOUND:     NPS_CLIENT_NOT_FOUND,
    SUBSCRIBE_LIMIT_EXCEEDED:       _NPS_LIMIT_EXCEEDED,
    SUBSCRIBE_FILTER_UNSUPPORTED:   NPS_SERVER_UNSUPPORTED,
    SUBSCRIBE_INTERRUPTED:          NPS_SERVER_UNAVAILABLE,
    SUBSCRIBE_SEQ_TOO_OLD:          NPS_CLIENT_CONFLICT,
    BUDGET_EXCEEDED:                NPS_LIMIT_BUDGET,
    CGN_LIMIT_EXCEEDED:             _NPS_CLIENT_REQUEST_TOO_LARGE,
    DEPTH_EXCEEDED:                 NPS_CLIENT_BAD_PARAM,
    GRAPH_CYCLE:                    NPS_CLIENT_UNPROCESSABLE,
    NODE_UNAVAILABLE:               NPS_SERVER_UNAVAILABLE,
    MANIFEST_VERSION_UNSUPPORTED:   NPS_CLIENT_BAD_PARAM,
    MANIFEST_NODE_TYPE_REMOVED:     NPS_CLIENT_BAD_FRAME,
    MANIFEST_NODE_TYPE_UNKNOWN:     NPS_CLIENT_BAD_FRAME,
    RATE_LIMIT_EXCEEDED:            NPS_LIMIT_RATE,
    RESERVED_TYPE_UNSUPPORTED:      NPS_SERVER_UNSUPPORTED,
    TOPOLOGY_UNAUTHORIZED:          NPS_AUTH_FORBIDDEN,
    TOPOLOGY_UNSUPPORTED_SCOPE:     NPS_CLIENT_BAD_PARAM,
    TOPOLOGY_DEPTH_UNSUPPORTED:     NPS_CLIENT_BAD_PARAM,
    TOPOLOGY_FILTER_UNSUPPORTED:    NPS_CLIENT_BAD_PARAM,
}
