# Copyright 2026 INNO LOTUS PTY LTD
# SPDX-License-Identifier: Apache-2.0

"""NPS NIP — Neural Identity Protocol frames and identity management."""

from nps_sdk.nip.frames import (
    IdentFrame,
    IdentLineage,
    IdentLineageRole,
    IdentMetadata,
    IdentReputationPolicyHint,
    RevokeFrame,
    TrustFrame,
)
from nps_sdk.nip.identity import NipIdentity
from nps_sdk.nip.ca_client import (
    NipCaClient,
    NipCaClientError,
    NipCaCrl,
    NipCaCrlEntry,
    NipCaDiscoveryDocument,
    NipCaIdentFrame,
    NipCaRegisterRequest,
    NipCaRegisterX509Request,
    NipCaRevokeFrame,
    NipCaVerifyResponse,
)
from nps_sdk.nip import error_codes
from nps_sdk.nip.error_codes import NIP_ERROR_TO_NPS_STATUS
from nps_sdk.nip.verifier import (
    NipCertRecord,
    NipIdentVerifier,
    NipIdentVerifyResult,
    NipRevocationCheck,
    NipRevocationStore,
    NipVerifierOptions,
    NipVerifyContext,
    nwp_path_matches,
)
from nps_sdk.nip.trust_validator import (
    TrustFrameValidationContext,
    TrustFrameValidator,
)
from nps_sdk.nip.reputation import (
    IncidentType,
    InclusionProof,
    ObservationWindow,
    ReputationLogClient,
    ReputationLogEntry,
    ReputationLogException,
    Severity,
    SignedTreeHead,
    sign_entry,
    verify_entry,
)
from nps_sdk.nip.ca import (
    AllowlistPolicy,
    BootstrapTokenInfo,
    BootstrapTokenPolicy,
    EnrollmentTier,
    FlattenedJws,
    IBootstrapTokenStore,
    IEnrollmentPolicy,
    INipCaStore,
    IPendingStore,
    InMemoryBootstrapTokenStore,
    InMemoryNipCaStore,
    InMemoryPendingStore,
    NipCaCertRecord,
    NipCaException,
    NipCaOptions,
    NipCaRouterApp,
    NipCaService,
    NipGroupJws,
    NipRaPendingException,
    NipVerifyResult,
    PendingQueuePolicy,
    PendingRegistration,
    PendingStatus,
    create_enrollment_policy,
)

__all__ = [
    "IdentFrame",
    "IdentLineage",
    "IdentLineageRole",
    "IdentMetadata",
    "IdentReputationPolicyHint",
    "RevokeFrame",
    "TrustFrame",
    "NipIdentity",
    "NipCaClient",
    "NipCaClientError",
    "NipCaCrl",
    "NipCaCrlEntry",
    "NipCaDiscoveryDocument",
    "NipCaIdentFrame",
    "NipCaRegisterRequest",
    "NipCaRegisterX509Request",
    "NipCaRevokeFrame",
    "NipCaVerifyResponse",
    "error_codes",
    "NIP_ERROR_TO_NPS_STATUS",
    "NipCertRecord",
    "NipIdentVerifier",
    "NipIdentVerifyResult",
    "NipRevocationCheck",
    "NipRevocationStore",
    "NipVerifierOptions",
    "NipVerifyContext",
    "nwp_path_matches",
    "TrustFrameValidationContext",
    "TrustFrameValidator",
    "IncidentType",
    "InclusionProof",
    "ObservationWindow",
    "ReputationLogClient",
    "ReputationLogEntry",
    "ReputationLogException",
    "Severity",
    "SignedTreeHead",
    "sign_entry",
    "verify_entry",
    # ── CA service library (NPS-3 §6–8, CR-0003, CR-0005, RFC-0002) ─────────
    "NipCaService",
    "NipCaOptions",
    "NipVerifyResult",
    "NipCaException",
    "NipCaCertRecord",
    "INipCaStore",
    "InMemoryNipCaStore",
    "EnrollmentTier",
    "IEnrollmentPolicy",
    "AllowlistPolicy",
    "BootstrapTokenPolicy",
    "IBootstrapTokenStore",
    "InMemoryBootstrapTokenStore",
    "BootstrapTokenInfo",
    "PendingQueuePolicy",
    "IPendingStore",
    "InMemoryPendingStore",
    "PendingRegistration",
    "PendingStatus",
    "NipRaPendingException",
    "create_enrollment_policy",
    "FlattenedJws",
    "NipGroupJws",
    "NipCaRouterApp",
]
