# Copyright 2026 INNO LOTUS PTY LTD
# SPDX-License-Identifier: Apache-2.0

"""NIP error code wire constants — mirror of `spec/error-codes.md` NIP section."""

from __future__ import annotations

# ── Cert verification (v1 + v2) ──────────────────────────────────────────────
CERT_EXPIRED            = "NIP-CERT-EXPIRED"
CERT_REVOKED            = "NIP-CERT-REVOKED"
CERT_SIGNATURE_INVALID  = "NIP-CERT-SIGNATURE-INVALID"
CERT_UNTRUSTED_ISSUER   = "NIP-CERT-UNTRUSTED-ISSUER"
CERT_CAPABILITY_MISSING = "NIP-CERT-CAPABILITY-MISSING"
CERT_SCOPE_VIOLATION    = "NIP-CERT-SCOPE-VIOLATION"

# ── CA service ───────────────────────────────────────────────────────────────
CA_NID_NOT_FOUND          = "NIP-CA-NID-NOT-FOUND"
CA_NID_ALREADY_EXISTS     = "NIP-CA-NID-ALREADY-EXISTS"
CA_SERIAL_DUPLICATE       = "NIP-CA-SERIAL-DUPLICATE"
CA_RENEWAL_TOO_EARLY      = "NIP-CA-RENEWAL-TOO-EARLY"
CA_SCOPE_EXPANSION_DENIED = "NIP-CA-SCOPE-EXPANSION-DENIED"

# ── CA group / session (NPS-3 §5.1.3 / NPS-CR-0003) ─────────────────────────
CA_GROUP_REVOKED          = "NIP-CA-GROUP-REVOKED"
CA_PARENT_NOT_FOUND       = "NIP-CA-PARENT-NOT-FOUND"
CA_PARENT_NOT_GROUP       = "NIP-CA-PARENT-NOT-GROUP"
CA_SESSION_VALIDITY_INVALID = "NIP-CA-SESSION-VALIDITY-INVALID"
CA_JWS_INVALID            = "NIP-CA-JWS-INVALID"
CA_JWS_EXPIRED            = "NIP-CA-JWS-EXPIRED"

OCSP_UNAVAILABLE        = "NIP-OCSP-UNAVAILABLE"
OCSP_STAPLE_EXPIRED     = "NIP-OCSP-STAPLE-EXPIRED"

# ── Trust frame (NPS-3 §5.2) ─────────────────────────────────────────────────
TRUST_FRAME_INVALID                = "NIP-TRUST-FRAME-INVALID"
TRUST_FRAME_EXPIRED                = "NIP-TRUST-FRAME-EXPIRED"
TRUST_FRAME_GRANTOR_REVOKED        = "NIP-TRUST-FRAME-GRANTOR-REVOKED"
TRUST_FRAME_SCOPE_EXCEEDS_GRANTOR  = "NIP-TRUST-FRAME-SCOPE-EXCEEDS-GRANTOR"
TRUST_FRAME_NODES_PATTERN_INVALID  = "NIP-TRUST-FRAME-NODES-PATTERN-INVALID"

# ── Revoke frame (NPS-3 §5.3) ────────────────────────────────────────────────
REVOKE_FRAME_INVALID              = "NIP-REVOKE-FRAME-INVALID"
REVOKE_FRAME_UNAUTHORIZED_ISSUER  = "NIP-REVOKE-FRAME-UNAUTHORIZED-ISSUER"
REVOKE_FRAME_SERIAL_MISMATCH      = "NIP-REVOKE-FRAME-SERIAL-MISMATCH"
REVOKE_FRAME_REASON_UNKNOWN       = "NIP-REVOKE-FRAME-REASON-UNKNOWN"

# ── RFC-0003 (assurance level) ───────────────────────────────────────────────
ASSURANCE_MISMATCH = "NIP-ASSURANCE-MISMATCH"
ASSURANCE_UNKNOWN  = "NIP-ASSURANCE-UNKNOWN"

# ── RFC-0004 (reputation log) ────────────────────────────────────────────────
REPUTATION_ENTRY_INVALID        = "NIP-REPUTATION-ENTRY-INVALID"
REPUTATION_LOG_UNREACHABLE      = "NIP-REPUTATION-LOG-UNREACHABLE"
REPUTATION_GOSSIP_FORK          = "NIP-REPUTATION-GOSSIP-FORK"
REPUTATION_GOSSIP_SIG_INVALID   = "NIP-REPUTATION-GOSSIP-SIG-INVALID"

# ── RFC-0002 (X.509 + ACME) ──────────────────────────────────────────────────
CERT_FORMAT_INVALID       = "NIP-CERT-FORMAT-INVALID"
CERT_EKU_MISSING          = "NIP-CERT-EKU-MISSING"
CERT_SUBJECT_NID_MISMATCH = "NIP-CERT-SUBJECT-NID-MISMATCH"
ACME_CHALLENGE_FAILED     = "NIP-ACME-CHALLENGE-FAILED"

# ── Chain / parent revocation (NPS-3 §5.1.3 / NPS-CR-0003) ──────────────────
CERT_PARENT_REVOKED       = "NIP-CERT-PARENT-REVOKED"

# ── Registration Authority enrollment (NPS-CR-0005 §3) ──────────────────────
RA_TOKEN_INVALID    = "NIP-RA-TOKEN-INVALID"
RA_TOKEN_EXPIRED    = "NIP-RA-TOKEN-EXPIRED"
RA_NID_NOT_ALLOWED  = "NIP-RA-NID-NOT-ALLOWED"
RA_PENDING_REJECTED = "NIP-RA-PENDING-REJECTED"

# ── NPS status mapping ────────────────────────────────────────────────────────
from nps_sdk.core.status_codes import (  # noqa: E402
    NPS_AUTH_FORBIDDEN,
    NPS_AUTH_UNAUTHENTICATED,
    NPS_CLIENT_BAD_FRAME,
    NPS_CLIENT_BAD_PARAM,
    NPS_CLIENT_CONFLICT,
    NPS_CLIENT_NOT_FOUND,
    NPS_DOWNSTREAM_UNAVAILABLE,
    NPS_SERVER_INTERNAL,
    NPS_SERVER_UNAVAILABLE,
)

NIP_ERROR_TO_NPS_STATUS: dict[str, str] = {
    CERT_EXPIRED:                       NPS_AUTH_UNAUTHENTICATED,
    CERT_REVOKED:                       NPS_AUTH_UNAUTHENTICATED,
    CERT_SIGNATURE_INVALID:             NPS_AUTH_UNAUTHENTICATED,
    CERT_UNTRUSTED_ISSUER:              NPS_AUTH_UNAUTHENTICATED,
    CERT_CAPABILITY_MISSING:            NPS_AUTH_FORBIDDEN,
    CERT_SCOPE_VIOLATION:               NPS_AUTH_FORBIDDEN,
    CERT_FORMAT_INVALID:                NPS_CLIENT_BAD_FRAME,
    CERT_EKU_MISSING:                   NPS_CLIENT_BAD_FRAME,
    CERT_SUBJECT_NID_MISMATCH:          NPS_CLIENT_BAD_FRAME,
    CERT_PARENT_REVOKED:                NPS_AUTH_UNAUTHENTICATED,
    CA_NID_NOT_FOUND:                   NPS_CLIENT_NOT_FOUND,
    CA_NID_ALREADY_EXISTS:              NPS_CLIENT_CONFLICT,
    CA_SERIAL_DUPLICATE:                NPS_CLIENT_CONFLICT,
    CA_RENEWAL_TOO_EARLY:               NPS_CLIENT_BAD_PARAM,
    CA_SCOPE_EXPANSION_DENIED:          NPS_AUTH_FORBIDDEN,
    CA_GROUP_REVOKED:                   NPS_AUTH_FORBIDDEN,
    CA_PARENT_NOT_FOUND:                NPS_CLIENT_NOT_FOUND,
    CA_PARENT_NOT_GROUP:                NPS_CLIENT_BAD_PARAM,
    CA_SESSION_VALIDITY_INVALID:        NPS_CLIENT_BAD_PARAM,
    CA_JWS_INVALID:                     NPS_AUTH_UNAUTHENTICATED,
    CA_JWS_EXPIRED:                     NPS_AUTH_UNAUTHENTICATED,
    RA_TOKEN_INVALID:                   NPS_AUTH_UNAUTHENTICATED,
    RA_TOKEN_EXPIRED:                   NPS_AUTH_UNAUTHENTICATED,
    RA_NID_NOT_ALLOWED:                 NPS_AUTH_FORBIDDEN,
    RA_PENDING_REJECTED:                NPS_AUTH_FORBIDDEN,
    OCSP_UNAVAILABLE:                   NPS_SERVER_UNAVAILABLE,
    OCSP_STAPLE_EXPIRED:                NPS_AUTH_UNAUTHENTICATED,
    TRUST_FRAME_INVALID:                NPS_CLIENT_BAD_FRAME,
    TRUST_FRAME_EXPIRED:                NPS_AUTH_UNAUTHENTICATED,
    TRUST_FRAME_GRANTOR_REVOKED:        NPS_AUTH_UNAUTHENTICATED,
    TRUST_FRAME_SCOPE_EXCEEDS_GRANTOR:  NPS_AUTH_FORBIDDEN,
    TRUST_FRAME_NODES_PATTERN_INVALID:  NPS_CLIENT_BAD_FRAME,
    REVOKE_FRAME_INVALID:               NPS_CLIENT_BAD_FRAME,
    REVOKE_FRAME_UNAUTHORIZED_ISSUER:   NPS_AUTH_FORBIDDEN,
    REVOKE_FRAME_SERIAL_MISMATCH:       NPS_CLIENT_BAD_PARAM,
    REVOKE_FRAME_REASON_UNKNOWN:        NPS_CLIENT_BAD_FRAME,
    ASSURANCE_MISMATCH:                 NPS_CLIENT_BAD_FRAME,
    ASSURANCE_UNKNOWN:                  NPS_CLIENT_BAD_FRAME,
    REPUTATION_ENTRY_INVALID:           NPS_CLIENT_BAD_FRAME,
    REPUTATION_LOG_UNREACHABLE:         NPS_DOWNSTREAM_UNAVAILABLE,
    REPUTATION_GOSSIP_FORK:             NPS_SERVER_INTERNAL,
    REPUTATION_GOSSIP_SIG_INVALID:      NPS_CLIENT_BAD_FRAME,
    ACME_CHALLENGE_FAILED:              NPS_CLIENT_BAD_FRAME,
}
