# Copyright 2026 INNO LOTUS PTY LTD
# SPDX-License-Identifier: Apache-2.0

"""NOP error code wire constants — mirror of `spec/error-codes.md` NOP section."""

from __future__ import annotations

# ── Task ──────────────────────────────────────────────────────────────────────
NOP_TASK_NOT_FOUND        = "NOP-TASK-NOT-FOUND"
NOP_TASK_TIMEOUT          = "NOP-TASK-TIMEOUT"
NOP_TASK_DAG_INVALID      = "NOP-TASK-DAG-INVALID"
NOP_TASK_DAG_CYCLE        = "NOP-TASK-DAG-CYCLE"
NOP_TASK_DAG_TOO_LARGE    = "NOP-TASK-DAG-TOO-LARGE"
NOP_TASK_ALREADY_COMPLETED = "NOP-TASK-ALREADY-COMPLETED"
NOP_TASK_CANCELLED        = "NOP-TASK-CANCELLED"

# ── Delegate ──────────────────────────────────────────────────────────────────
NOP_DELEGATE_SCOPE_VIOLATION  = "NOP-DELEGATE-SCOPE-VIOLATION"
NOP_DELEGATE_REJECTED         = "NOP-DELEGATE-REJECTED"
NOP_DELEGATE_CHAIN_TOO_DEEP   = "NOP-DELEGATE-CHAIN-TOO-DEEP"
NOP_DELEGATE_TIMEOUT          = "NOP-DELEGATE-TIMEOUT"

# ── Sync ──────────────────────────────────────────────────────────────────────
NOP_SYNC_TIMEOUT           = "NOP-SYNC-TIMEOUT"
NOP_SYNC_DEPENDENCY_FAILED = "NOP-SYNC-DEPENDENCY-FAILED"

# ── Stream ────────────────────────────────────────────────────────────────────
NOP_STREAM_SEQ_GAP     = "NOP-STREAM-SEQ-GAP"
NOP_STREAM_NID_MISMATCH = "NOP-STREAM-NID-MISMATCH"
# alpha.11 addition (AlignStream ack/NAK protocol):
NOP_STREAM_NAK         = "NOP-STREAM-NAK"

# ── Resources ─────────────────────────────────────────────────────────────────
NOP_RESOURCE_INSUFFICIENT = "NOP-RESOURCE-INSUFFICIENT"

# ── DAG execution ─────────────────────────────────────────────────────────────
NOP_CONDITION_EVAL_ERROR    = "NOP-CONDITION-EVAL-ERROR"
NOP_INPUT_MAPPING_ERROR     = "NOP-INPUT-MAPPING-ERROR"
NOP_COMPENSATION_FAILED     = "NOP-COMPENSATION-FAILED"
NOP_COMPENSATION_PARTIAL_FAILED = "NOP-COMPENSATION-PARTIAL-FAILED"
NOP_COMPENSATION_NOT_SUPPORTED = "NOP-COMPENSATION-NOT-SUPPORTED"

# ── Webhook / callback (alpha.11+) ────────────────────────────────────────────
NOP_CALLBACK_HMAC_MISSING = "NOP-CALLBACK-HMAC-MISSING"
NOP_CALLBACK_INVALID = "NOP-CALLBACK-INVALID"
NOP_CALLBACK_HMAC_INVALID = "NOP-CALLBACK-HMAC-INVALID"

# ── NPS-CR-0007 L3 runtime ────────────────────────────────────────────────────
NOP_CLAIM_CONFLICT = "NOP-CLAIM-CONFLICT"
NOP_SPAWN_SPEC_INVALID = "NOP-SPAWN-SPEC-INVALID"
NOP_RUNTIME_IDLE_TIMEOUT = "NOP-RUNTIME-IDLE-TIMEOUT"
NOP_RUNTIME_MAX_RUNTIME = "NOP-RUNTIME-MAX-RUNTIME"

# ── Result retention / retransmission (NOP v0.7) ─────────────────────────────
NOP_TASK_RESULT_EXPIRED = "NOP-TASK-RESULT-EXPIRED"
NOP_STREAM_NAK_UNRESOLVABLE = "NOP-STREAM-NAK-UNRESOLVABLE"

# ── NPS status mapping ────────────────────────────────────────────────────────
from nps_sdk.core.status_codes import (  # noqa: E402
    NPS_AUTH_FORBIDDEN,
    NPS_AUTH_UNAUTHENTICATED,
    NPS_CLIENT_BAD_FRAME,
    NPS_CLIENT_BAD_PARAM,
    NPS_CLIENT_CONFLICT,
    NPS_CLIENT_NOT_FOUND,
    NPS_CLIENT_UNPROCESSABLE,
    NPS_SERVER_TIMEOUT,
    NPS_SERVER_UNAVAILABLE,
    NPS_STREAM_SEQ_GAP,
)

NOP_ERROR_TO_NPS_STATUS: dict[str, str] = {
    NOP_TASK_NOT_FOUND:            NPS_CLIENT_NOT_FOUND,
    NOP_TASK_TIMEOUT:              NPS_SERVER_TIMEOUT,
    NOP_TASK_DAG_INVALID:          NPS_CLIENT_BAD_FRAME,
    NOP_TASK_DAG_CYCLE:            NPS_CLIENT_BAD_FRAME,
    NOP_TASK_DAG_TOO_LARGE:        NPS_CLIENT_BAD_FRAME,
    NOP_TASK_ALREADY_COMPLETED:    NPS_CLIENT_CONFLICT,
    NOP_TASK_CANCELLED:            NPS_CLIENT_CONFLICT,
    NOP_DELEGATE_SCOPE_VIOLATION:  NPS_AUTH_FORBIDDEN,
    NOP_DELEGATE_REJECTED:         NPS_CLIENT_UNPROCESSABLE,
    NOP_DELEGATE_CHAIN_TOO_DEEP:   NPS_CLIENT_BAD_PARAM,
    NOP_DELEGATE_TIMEOUT:          NPS_SERVER_TIMEOUT,
    NOP_SYNC_TIMEOUT:              NPS_SERVER_TIMEOUT,
    NOP_SYNC_DEPENDENCY_FAILED:    NPS_CLIENT_UNPROCESSABLE,
    NOP_STREAM_SEQ_GAP:            NPS_STREAM_SEQ_GAP,
    NOP_STREAM_NID_MISMATCH:       NPS_AUTH_UNAUTHENTICATED,
    NOP_STREAM_NAK:                NPS_STREAM_SEQ_GAP,
    NOP_RESOURCE_INSUFFICIENT:     NPS_SERVER_UNAVAILABLE,
    NOP_CONDITION_EVAL_ERROR:      NPS_CLIENT_BAD_PARAM,
    NOP_INPUT_MAPPING_ERROR:       NPS_CLIENT_UNPROCESSABLE,
    NOP_COMPENSATION_FAILED:       NPS_CLIENT_UNPROCESSABLE,
    NOP_COMPENSATION_PARTIAL_FAILED: NPS_CLIENT_UNPROCESSABLE,
    NOP_COMPENSATION_NOT_SUPPORTED: NPS_CLIENT_UNPROCESSABLE,
    NOP_CALLBACK_HMAC_MISSING:     NPS_AUTH_UNAUTHENTICATED,
    NOP_CALLBACK_INVALID:          NPS_CLIENT_BAD_PARAM,
    NOP_CALLBACK_HMAC_INVALID:     NPS_AUTH_UNAUTHENTICATED,
    NOP_CLAIM_CONFLICT:            NPS_CLIENT_CONFLICT,
    NOP_SPAWN_SPEC_INVALID:        NPS_CLIENT_BAD_PARAM,
    NOP_RUNTIME_IDLE_TIMEOUT:      NPS_SERVER_TIMEOUT,
    NOP_RUNTIME_MAX_RUNTIME:       NPS_SERVER_TIMEOUT,
    NOP_TASK_RESULT_EXPIRED:       NPS_CLIENT_NOT_FOUND,
    NOP_STREAM_NAK_UNRESOLVABLE:   NPS_STREAM_SEQ_GAP,
}
